export const books=[
    {
    id: 1,
    title: "Crack the coding interview",
    url: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    originalPrice: 1050,
    salePrice: 900,
    rating: 5.0,
  },
  {
    id: 2,
    title: "Atomic Habits",
    url:"https://covers.openlibrary.org/b/id/10958382-L.jpg",
    originalPrice: 2010,
    salePrice: 2050,
    rating: 3.5,
  },
  {
    id: 3,
    title: "Can't hurt me",
    url: "https://covers.openlibrary.org/b/id/10425061-L.jpg",
    originalPrice: 575,
    salePrice: 345,
    rating: 2.5,
  },
  {
    id: 4,
    title: "Deep Work",
    url: "https://covers.openlibrary.org/b/id/10088428-L.jpg",
    originalPrice: 665,
    salePrice: 485,
    rating: 4.0,
  },
  {
    id: 5,
    title: "THE 10X RULE",
    url: "https://covers.openlibrary.org/b/id/9978588-L.jpg",
    originalPrice: 769,
    salePrice: 650,
    rating: 5.0,
  },
  {
    id: 6,
    title: "Sell or Be Sold",
    url: "https://covers.openlibrary.org/b/id/7737110-L.jpg",
    originalPrice: 975,
    salePrice: 845,
    rating: 4.5,
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    url: "https://covers.openlibrary.org/b/id/2380224-L.jpg",
    originalPrice: 1575,
    salePrice: 1345,
    rating: 5.0,
  },
  {
    id: 8,
    title:" Cashflow quadrant",
    url:"https://covers.openlibrary.org/b/id/1954899-L.jpg",
    originalPrice: 1275,
    salePrice: 1045,
    rating: 4.5,
  },
  {
    id: 9,
    title:" Summary of The 48 Laws of Power",
    url: "https://covers.openlibrary.org/b/id/8906626-L.jpg",
    originalPrice: 49.95,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 10,
    title:" The 5 Second Rule",
    url: "https://covers.openlibrary.org/b/id/8114155-L.jpg",
    originalPrice: 2075,
    salePrice: null,
    rating: 4.0
  },
  {
    id: 11,
    title: "IKIGAI",
    url: "https://covers.openlibrary.org/b/id/12306248-L.jpg",
    originalPrice: 2575,
    salePrice: null,
    rating: 5.0,
  },
  {
  id: 12,
    title: "Mastery",
    url: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
    originalPrice: 799,
    salePrice: null,
    rating: 5.0,
  },
];